// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDeviceButtons(arg1) {
  return window['go']['main']['App']['GetDeviceButtons'](arg1);
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetWheelActions(arg1) {
  return window['go']['main']['App']['GetWheelActions'](arg1);
}

export function SetButtonAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetButtonAction'](arg1, arg2, arg3);
}

export function SetWheelAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetWheelAction'](arg1, arg2, arg3);
}
